services:
  mysql:
    image: mysql:8.4
    container_name: bidinsouk-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bidinsouk
      MYSQL_USER: bid
      MYSQL_PASSWORD: bid
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: